config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'
  resources :events do
    # post 'events/:id', to: 'comments#create'
    resources :comments, only: [:create]
  end  
  resources :comments, only: [:destroy]
  # get 'comments/create_comment', to: 'comments#create_comment'
  # post 'events/:id', to: 'comments#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: 'バスケットボール' }, { id: 3, name: 'フットサル' },
    { id: 4, name: 'テニス' }, { id: 5, name: '野球' }, { id: 6, name: 'バレーボール' },
    { id: 7, name: 'パークゴルフ' }, { id: 8, name: 'バトミントン' }, { id: 9, name: '卓球' },
    { id: 10, name: 'ボウリング' }, { id: 11, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :events
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :text,  presence: true
end

app/models/delivery_area.rb
class DeliveryArea < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many   :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :delivery_area
  belongs_to :time_all
  

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :delivery_area_id
    validates :time_all_id
  end

  with_options presence: true do
    validates :product
    validates :introduction
    validates :price, numericality: { greater_than_or_equal_to: 200, less_than_or_equal_to: 99_999 },
                      format: { with: /\A[0-9]+\z/ }
    validates :start
    validates :time_start
  end  
end

app/models/time_all.rb
class TimeAll < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '1時間' }, { id: 3, name: '1時間半' },
    { id: 4, name: '2時間' }, { id: 5, name: '2時間半' }, { id: 6, name: '3時間' },
    { id: 7, name: '3時間半' }, { id: 8, name: '4時間' }, { id: 9, name: '4時間半' },
    { id: 10, name: '5時間以上' }, { id: 11, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :first_name,        format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :family_name,       format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :first_name_kana,   format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :family_name_kana,  format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birthday
    validates :gender
  end
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }
  enum gender: { man: 0, woman: 1 }

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :family_name, :first_name_kana, :family_name_kana, :birthday, :gender])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  

  def create
    # ------------------------------------------------------------------------
      @event = Event.find(params[:event_id])
      @comment = Comment.new(comment_params)         # データベース内の処理
       if @comment.save
      # @comment = Comment.create(text: params[:text]) 
      # render json:{post: text}
    # ------------------------------------------------------------------------
    # ------------------------------------------------------------------------
      respond_to do |format|
        format.html  # { redirect_to event_path(params[:event_id]) }
        format.json # { render json: @comment}                        # データベースの処理が終わったあとどうするのか
      end
    else
      flash.now[:alert] = 'メッセージを入力または画像を送信してください'
      redirect_to "/events/#{comment.event.id}"
    end
    # ------------------------------------------------------------------------
   
    
    end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to "/events/#{comment.event.id}"
  end  

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, event_id: params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:destroy, :show, :edit, :update]
  before_action :login_user, only: [:destroy, :edit]
  
  def index
    @events = Event.includes(:user).order(created_at: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @event.comments.includes(:user).order(created_at: :desc)
  end 
  
  def edit
  end  

  def update
    if @event.update(event_params)
      redirect_to event_path
    else
      render :edit
    end
  end

  def destroy
    
    @event.destroy
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit( :product, :introduction, :category_id,  :price, :time_all_id, :delivery_area_id, :start, :time_start).merge(user_id: current_user.id)
  end

  def login_user
    redirect_to root_path unless current_user.id == @event.user_id
  end

  def set_event
    @event = Event.find(params[:id])
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/event/index.html.erb
<body>

<div id="container">



          <header>
            <%= link_to image_tag("logo4.png", class: :logo), root_path %>
            <aside id="mainimg"><%= link_to image_tag("test3.jpg", class: :img) %></aside>
            
           </header>   
          
<nav id="menubar">
<ul>
<li><%= link_to 'ホーム', root_path %></li>

<% if user_signed_in? %>
        <li><%= link_to 'イベント投稿', root_path %></li>
        <li><%= link_to current_user.nickname, root_path  %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>


</ul>
</nav>

<div id="contents">

<section id="new">
<h2>更新情報・お知らせ</h2>
<dl>
<dt>2019/04/22</dt>
<dd>より初心者が使いやすいよう少し調整。古いものを使っている人はそのままでOKです。</dd>
<dt>2017/10/06</dt>
<dd>初心者向け無料ホームページテンプレートtp_beginner5公開。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
</dl>
</section>

<section>

<h2>新規イベント</h2>

<h3>利用規約のご案内</h3>
<p>このテンプレートは、<a href="https://template-party.com/">Template Party</a>にて無料配布している『初心者向けホームページテンプレート tp_beginner5』です。必ずダウンロード先のサイトの<a href="https://template-party.com/read.html">利用規約</a>をご一読の上でご利用下さい。</p>
<p><span class="color1">■<strong>HP最下部の著作表示『Web Design:Template-Party』は無断で削除しないで下さい。</strong></span><br>
わざと見えなく加工する事も禁止です。</p>
<p><span class="color1">■<strong>下部の著作を外したい場合は</strong></span><br>
<a href="https://template-party.com/">Template-Party</a>の<a href="https://template-party.com/member.html">ライセンス契約</a>を行う事でHP下部の著作を外す事ができます。</p>

<h3>ご不明点</h3>
<p><a href="about.html">こちらをご覧下さい。</a></p>

</section>

</div>
<!--/contents-->

<footer>
<small>Copyright&copy; <a href="index.html">SAMPLE SITE</a> All Rights Reserved.</small>
<span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>

</div>
<!--/container-->

</body>
</html>

app/views/events/edit.html.erb
<header>
  <%= link_to image_tag("logo4.png", class: :logo), root_path %>
           
<nav id="menubar">
<ul>
        <li><%= link_to 'ホーム', root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'イベント投稿', new_event_path %></li>
        <li><%= link_to current_user.nickname, root_path  %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
</ul>
</nav>
</header> 

<div class="items-sell-main">
    <h2 class="items-sell-title">イベントの情報を入力</h2>
    <%= form_with model: @event, local: true do |f| %>

    <%= render 'shared/error_messages', model:@event %>

    
    <%# イベント名とイベント説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        イベント名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product, class:"items-text", id:"item-name", placeholder:"イベント名（必須 15文字まで)", maxlength:"15" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          イベントの詳細
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info", placeholder:"イベントの説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    

    <%# イベントの詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">イベントの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          所要時間
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:time_all_id, TimeAll.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
         
         <div class="weight-bold-text">
          開催の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_area_id, DeliveryArea.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>

        <div class="weight-bold-text">
          開始日
          <span class="indispensable">必須</span>
        </div>
        <%= f.date_field :start, class: 'items-text' %>
        <div class="weight-bold-text">
          開始時間
          <span class="indispensable">必須</span>
        </div>
        <%= f.time_select :time_start, class: 'items-text' %>
      </div> 
    </div>
    <%# /商品の詳細 %>

    

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥200〜99,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>手数料 (5%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>イベント利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている行為</a>
       
        を必ずご確認ください。
      </p>
      <p class="sentence">
        詳しい開催地は詳細の方へご記載ください。
      
      </p>
      <p class="sentence">
        また、イベント主催をもちまして
        <a href="#">利用規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/events/index.html.erb
<body>

<div id="container">

<header>
  <%= link_to image_tag("logo4.png", class: :logo), root_path %>
  <aside id="mainimg"><%= link_to image_tag("test3.jpg", class: :img) %></aside>         
<nav id="menubar">
<ul>
        <li><%= link_to 'ホーム', root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'イベント投稿',  new_event_path %></li>
        <li><%= link_to current_user.nickname, root_path  %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
</ul>
</nav>
</header> 
<div id="contents">

<section id="new">
<h2>更新情報・お知らせ</h2>
<dl>
<dt>2020/11/22</dt>
<dd>新機機能の追加しました。</dd>
<dt>2020/11/20</dt>
<dd>オリジナルアプリ作成し始めました。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>

</dl>
</section>

<section id="new">
<h2>新規イベント</h2>


<% @events.each do |event| %>
<div class="list">
<dt><%= event.start.strftime('%Y/%m/%d') %></dt><dd><h4><%= link_to event.product, event_path(event.id) %></h4></dd>
<dl>
<dt><p>カテゴリー：</p></dt><dd><%= event.category.name %></dd>
<dt><p>開催地域：</p></dt><dd><%= event.delivery_area.name %></dd>
<dt><p>開始時間：</p></dt><dd><%= event.time_start.strftime('%H:%M') %>〜（<%= event.time_all.name %>）</dd>
<dt><p>参加料金：</p></dt><dd><%= event.price %>円</dd>
</dl>
</div>
<% end %>
</section>

<h1>Ajax#index</h1>
<p id="hoge">赤色になるよ</p>

<script>
  $("#hoge").css("color","red")
</script>

<script>
  $("#test").html("ミッションコンプリート！");
  $("#test").css("color","red");
</script>

<section>

<%= render "shared/footer" %>

</body>
</html>

app/views/events/new.html.erb
<header>
  <%= link_to image_tag("logo4.png", class: :logo), root_path %>
           
<nav id="menubar">
<ul>
        <li><%= link_to 'ホーム', root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'イベント投稿', new_event_path %></li>
        <li><%= link_to current_user.nickname, root_path  %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
</ul>
</nav>
</header> 

<div class="items-sell-main">
    <h2 class="items-sell-title">イベントの情報を入力</h2>
    <%= form_with model: @event, local: true do |f| %>

    <%= render 'shared/error_messages', model:@event %>

    
    <%# イベント名とイベント説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        イベント名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product, class:"items-text", id:"item-name", placeholder:"イベント名（必須 15文字まで)", maxlength:"15" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          イベントの詳細
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info", placeholder:"イベントの説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    

    <%# イベントの詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">イベントの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          所要時間
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:time_all_id, TimeAll.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
         
         <div class="weight-bold-text">
          開催の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_area_id, DeliveryArea.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>

        <div class="weight-bold-text">
          開始日
          <span class="indispensable">必須</span>
        </div>
        <%= f.date_field :start, class: 'items-text' %>
        <div class="weight-bold-text">
          開始時間
          <span class="indispensable">必須</span>
        </div>
        <%= f.time_select :time_start, class: 'items-text' %>
      </div> 
    </div>
    <%# /商品の詳細 %>

    

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥200〜99,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>手数料 (5%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>イベント利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている行為</a>
       
        を必ずご確認ください。
      </p>
      <p class="sentence">
        詳しい開催地は詳細の方へご記載ください。
      
      </p>
      <p class="sentence">
        また、イベント主催をもちまして
        <a href="#">利用規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/events/show.html.erb
<body>

<div id="container">

<header>
  <%= link_to image_tag("logo4.png", class: :logo), root_path %>
           
<nav id="menubar">
<ul>
        <li><%= link_to 'ホーム', root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'イベント投稿', new_event_path %></li>
        <li><%= link_to current_user.nickname, root_path  %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
</ul>
</nav>
</header> 



<div id="contents">

<section>

<h2>主催者名</h2>
<p>このサイトの<%= link_to @event.user.nickname, root_path %>さんのイベントページです。</p>

<h2>イベント詳細</h2>
<table class="ta1">
<caption><%= @event.product %></caption>
<tr>
<th>開催時間</th>
<td><%= @event.start.strftime('%Y/%m/%d ') %><%= @event.time_start.strftime('%H:%M') %>〜</td>
</tr>
<tr>
<th>所要時間</th>
<td><%= @event.time_all.name %></td>
</tr>
<tr>
<th>カテゴリー</th>
<td><%= @event.category.name %></td>
</tr>
<tr>
<th>開催地域</th>
<td><%= @event.delivery_area.name %></td>
</tr>
<tr>
<th>参加料金</th>
<td><%= @event.price %>円</td>
</tr>
<tr>
<th>イベント内容</th>
<td><%= @event.introduction %></td>
</tr>
</table>

</section>

<h2>イベントについて</h2>
 <% if  user_signed_in? && current_user.id == @event.user_id %>
    <%= link_to 'イベントの編集', edit_event_path, method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', event_path, method: :delete, class:'item-red-btn' %>
    <% elsif user_signed_in? %>
    
    <%= link_to 'イベント参加画面に進む', root_path, class:"item-red-btn"%>
   
    <% else %>
  <% end %>



<h2>コメント</h2>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@event, @comment],  remote: true, id: "form") do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2", id: "text" %>
        <%= form.submit "SEND", id: "submit" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
  

<div class="comments">
      <h4>＜コメント一覧＞</h4>
      
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, root_path %>：</strong>
            <%= comment.text %>
            <%= link_to '(削除)', comment_path(comment.id), method: :delete %>
          </p>
        <% end %>
    
    </div>

<%= render "shared/footer" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Sports planning</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
</head>
<header class="header">
      <div class="inner">
        <div class="nav">
        
 
          
        </div>
      </div>
    </header>
<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<section>

<h3>利用規約のご案内</h3>
<p>オリジナルアプリ作るにあったって使用した他サイトの詳細です。</p>
<p><span class="color1">■<strong>「Sports planning」のロゴ</strong></span><br>
<a href="https://www.squarespace.com/logo/#N4IghgrgLgFgpgExALigJwnAvkA">Squarespace Logo</a>を使用させていただきました。</p>

<p><span class="color1">■<strong>ホームページテンプレート</strong></span><br>
<a href="https://template-party.com/">Template Party</a>にて無料配布されている物を使用させていただきました。</p>

<h3>ご不明点</h3>
<p>こちらをご覧下さい。</p>

</section>

</div>
<!--/contents-->

<footer>
<small>Copyright&copy; <a href="index.html">SAMPLE SITE</a> All Rights Reserved.</small>
<span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>

</div>
<!--/container-->